import React from "react";
import Card from "../Card/Card";
import { AiFillStar } from "react-icons/ai";

function ProductsPage() {
  const Products = [
    {
      img: "https://assets.ajio.com/medias/sys_master/root/20240507/mdc0/663a557116fd2c6e6af0ef6f/-473Wx593H-467293008-brown-MODEL.jpg",
      title: " Campus Sutra",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Urban Ascot",
      color: "white",
      category: "Men-shirts",
    },
    {
      img: "https://assets.ajio.com/medias/sys_master/root/20240515/8Eft/6644e22b16fd2c6e6a09de42/-473Wx593H-467334866-brown-MODEL.jpg",
      title: "Men Stripeed Regular Fit Shirt",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Valor & Vogue",
      color: "red",
      category: "Men-shirts",
    },

    {
      img: "https://assets.ajio.com/medias/sys_master/root/20240212/mzAh/65ca1cd605ac7d77bb506235/indian-needle-wine-classic-men-regular-fit-shirt.jpg",
      title: "The Modern Man's Closet",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Heritage & Hype",
      color: "green",
      category: "Men-shirts",
    },
    {
      img: "https://assets.ajio.com/medias/sys_master/root/20240211/WOQ3/65c8cf8916fd2c6e6aef57af/indian-needle-brown-classic-men-checked-regular-fit-shirt.jpg",
      title: "Tailored for Him",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Noble Threads",
      color: "black",
      category: "Men-shirts",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rv0alr4byk/design-up-mens-maroon-solid-pure-cotton-shirt-l-shirt-shirts-cotton-shirt-cotton-shirts-casual-shirts-formal-shirts-cotton-men-shirt-men-shirts-product-images-rv0alr4byk-0-202210282102.jpg?im=Resize=(600,750)",
      title: "Elite Men's Style",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Prime Wardrobe",
      color: "green",
      category: "Men-shirts",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rv36rhe2e2/design-up-mens-multicolor-checkered-pure-cotton-shirt-xxl-shirt-shirts-cotton-shirt-cotton-shirts-casual-shirts-formal-shirts-cotton-men-shirt-men-shirts-product-images-rv36rhe2e2-0-202210282152.jpg?im=Resize=(600,750)",
      title: "Man's Style Avenue",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Tailored Terrain",
      color: "black",
      category: "Men-shirts",
    },

    {
      img: "https://www.jiomart.com/images/product/original/rvqx6hn6zm/design-up-mens-black-solid-pure-cotton-shirt-xl-shirt-shirts-cotton-shirt-cotton-shirts-casual-shirts-formal-shirts-cotton-men-shirt-men-shirts-product-images-rvqx6hn6zm-0-202211010620.jpg?im=Resize=(330,410)",
      title: "Gentlemen's Wardrobe",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Manor Mode",
      color: "white",
      category: "Men-shirts",
    },

    {
      img: "https://www.jiomart.com/images/product/original/rvkzlxusxd/design-up-mens-beige-solid-pure-cotton-shirt-m-shirt-shirts-cotton-shirt-cotton-shirts-casual-shirts-formal-shirts-cotton-men-shirt-men-shirts-product-images-rvkzlxusxd-0-202210282101.jpg?im=Resize=(330,410)",
      title: "Maverick Menswear",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "green",
      category: "Men-shirts",
    },

    {
      img: "https://www.jiomart.com/images/product/original/rvkczijqfa/design-up-mens-pink-solid-pure-cotton-shirt-l-shirt-shirts-cotton-shirt-cotton-shirts-casual-shirts-formal-shirts-cotton-men-shirt-men-shirts-product-images-rvkczijqfa-2-202211010623.jpg?im=Resize=(600,750)",
      title: "Dapper Men's Collection",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Gentleman's Code",
      color: "blue",
      category: "Men-shirts",
    },

    {
      img: "https://www.jiomart.com/images/product/original/rvwmlodbas/gespo-black-teal-blue-colorblocked-round-neck-half-sleeve-casual-t-shirt-product-images-rvwmlodbas-0-202304131033.jpg?im=Resize=(600,750)",
      title: "Half Sleeve Casual T-Shirt",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Stately Gents ",
      color: "green",
      category: "Men-shirts",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rvvoyivpw2/fabflee-party-printed-women-s-top-women-tops-crepe-top-tops-for-women-tops-for-women-product-images-rvvoyivpw2-0-202311022126.jpg?im=Resize=(330,410)",
      title: "Her Fashion Closet",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Velvet & Vine",
      color: "red",
      category: "Women",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rvuce3zqv7/fabflee-women-printed-pure-cotton-tshirt-black_xl-product-images-rvuce3zqv7-0-202212150924.jpg?im=Resize=(330,410)",
      title: "Glamour Wardrobe",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "black",
      category: "Women",
    },
    {
      img: "https://www.jiomart.com/images/product/original/443048353_jetblack/women-printed-cotton-boxy-fit-round-neck-t-shirt-model-443048353_jetblack-0-202408071912.jpg?im=Resize=(330,410)",
      title: "Chic Femme Fashion",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Luxe & Lace",
      color: "white",
      category: "Women",
    },
    {
      img: "https://www.jiomart.com/images/product/original/420474167_pink/women-floral-print-top-model-420474167_pink-0-202408091240.jpg?im=Resize=(330,410)",
      title: "Femme Flair",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Femme Finesse",
      color: "black",
      category: "Women",
    },

    {
      img: "https://www.jiomart.com/images/product/original/443016208_pink/typographic-print-cropped-sweatshirt-model-443016208_pink-0-202307271641.jpg?im=Resize=(330,410)",
      title: "Divine Divas Collection",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Femme Finesse",
      color: "green",
      category: "Women",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rvtleciknf/fabflee-women-white-crepe-kaftan-dress-white-product-images-rvtleciknf-0-202209240141.jpg?im=Resize=(330,410)",
      title: "Modern Muse Apparel",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Couture Bloom",
      color: "red",
      category: "Women",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rvqijrykka/fabflee-women-printed-casual-crepe-ethnic-top-product-images-rvqijrykka-0-202407191138.jpg?im=Resize=(330,410)",
      title: "Femme Flair",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Chic Essence",
      color: "white",
      category: "Women",
    },
    {
      img: "https://www.jiomart.com/images/product/original/420467156_offwhite/women-trucker-jackets-with-flap-pockets-model-420467156_offwhite-0-202408101540.jpg?im=Resize=(330,410)",
      title: "Vans Unisex Low-Top",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Chic Essence",
      color: "blue",
      category: "Women",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rvgsmtj941/fabflee-women-black-crepe-kaftan-dress-black-product-images-rvgsmtj941-0-202209211058.jpg?im=Resize=(330,410)",
      title: "Elegance Boutique",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Chic Essence",
      color: "black",
      category: "Women",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rvozfphdgm/fabflee-party-flared-sleeves-printed-women-green-top-women-tops-crepe-top-tops-for-women-product-images-rvozfphdgm-0-202309260656.jpg?im=Resize=(330,410)",
      title: "Chic Femme Fashion",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Grace & Glimmer",
      color: "black",
      category: "Women",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rvz0excawt/smartraho-boys-casual-t-shirt-track-pants-product-images-rvz0excawt-0-202301202143.jpg?im=Resize=(330,410)",
      title: "Cute & Comfy",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Mini Marvels",
      color: "black",
      category: "Kids",
    },
    {
      img: "https://www.jiomart.com/images/product/original/rvxeyixqyx/hellcat-trendy-black-graphic-printed-typo-graphic-cotton-blend-crew-neck-round-neck-half-sleeve-t-shirt-for-boys-product-images-rvxeyixqyx-0-202406061404.jpg?im=Resize=(330,410)",
      title: "Playful Threadss",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Mini Marvels",
      color: "red",
      category: "Kids",
    },
    {
      img: "https://f.media-amazon.com/images/I/81IowHFLS-L._SY741_.jpg",
      title: "Kiddie Closet",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Mini Marvelske",
      color: "red",
      category: "Kids",
    },

    {
      img: "https://assets.ajio.com/medias/sys_master/root/20220617/VjoJ/62ac9714f997dd03e28d95d4/kg-frendz-yellow-round-floral-print-round-neck-t-shirt.jpg",
      title: "Tiny Trendsetters",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Playful Pals",
      color: "black",
      category: "Kids",
    },
    {
      img: "https://f.media-amazon.com/images/G/31/img2020/img21/kids/2024/SS24/Boy/Featured/1/Gini_and_Jonyboys_564x940._SX564_QL85_FMpng_.png",
      title: "Chunky High Heel",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Playful Pals",
      color: "black",
      category: "Kids",
    },
    {
      img: "https://assets.ajio.com/medias/sys_master/root/20240704/oTEV/668726eb6f60443f31708eca/-473Wx593H-443051061-green-MODEL.jpg",
      title: "Little Style Icons",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Playful Pals",
      color: "white",
      category: "Kids",
    },
    {
      img: "https://assets.ajio.com/medias/sys_master/root/20230228/20Dy/63fe12d5aeb26924e398a0a1/birthdaygirl-yellow-regular-dora-print-round-neck-top.jpg",
      title: "Bridal Sandals Glitter",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Joyful Journeys",
      color: "black",
      category: "Kids",
    },
    {
      img: "https://assets.ajio.com/medias/sys_master/root/20230317/7Mz6/64142f38aeb26924e3caeb8b/max-lavender-regular-graphic-print-round-neck-top.jpg",
      title: "Junior Fashionistas",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Joyful Journeys",
      color: "black",
      category: "Kids",
    },
  ];
  // const propp = { img, title, star, reviews, prevPrice, newPrice };
  return (
    <section className="max-w-7xl mx-auto px-3 sm:px-5 py-24">
      <div className="flex flex-wrap gap-5 justify-center">
        {Products.map((item, index) => (
          <Card key={index} {...item} />
        ))}
      </div>
    </section>
  );
}

export default ProductsPage;
